import React from 'react';
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { 
  FileText, Shield, Brain, Users, ArrowRight, 
  AlertTriangle, Activity, Heart, TrendingUp 
} from "lucide-react";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, Area, AreaChart } from 'recharts';
import { format } from 'date-fns';

const focusGroupNames = {
  'postpartum-depression': 'Postpartum Support',
  'anxiety-management': 'Anxiety & Calm',
  'workplace-stress': 'Work-Life Balance'
};

const genderLabels = {
  'female': 'Female / She/Her',
  'male': 'Male / He/Him',
  'non-binary': 'Non-binary / They/Them',
  'prefer-not-to-say': 'Not Specified'
};

export default function MentraReport({ reportData, onJoinGroup }) {
  const {
    assessment,
    sentimentAnalysis,
    conversationSummary,
    emotionTrajectory,
    behavioralSnapshot,
    riskSummary
  } = reportData;

  const getESIColor = (score) => {
    if (score >= 70) return 'text-green-600';
    if (score >= 40) return 'text-amber-600';
    return 'text-red-600';
  };

  const getTRIColor = (score) => {
    if (score >= 70) return 'text-green-600';
    if (score >= 40) return 'text-amber-600';
    return 'text-red-600';
  };

  const getRiskColor = (level) => {
    if (level === 'low') return 'bg-green-100 text-green-700 border-green-200';
    if (level === 'moderate') return 'bg-amber-100 text-amber-700 border-amber-200';
    return 'bg-red-100 text-red-700 border-red-200';
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-6 max-w-3xl mx-auto"
    >
      {/* Header */}
      <Card className="border-0 shadow-lg overflow-hidden">
        <div className="bg-gradient-to-r from-slate-800 to-slate-700 text-white p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-xl bg-white/10 flex items-center justify-center">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-xl font-bold">MENTRA THERAPY INTAKE & HANDOFF REPORT</h1>
              <p className="text-white/70 text-sm">Generated by AI Orchestration System – Confidential</p>
            </div>
          </div>
          <div className="flex flex-wrap gap-4 text-sm">
            <div><span className="text-white/60">Date:</span> {format(new Date(), 'MMM dd, yyyy')}</div>
            <div><span className="text-white/60">Client ID:</span> {assessment.id?.slice(0, 8) || 'Anonymous'}</div>
            <div><span className="text-white/60">Focus Group:</span> {focusGroupNames[assessment.final_focus_group]}</div>
          </div>
        </div>
      </Card>

      {/* Section 1: Basic Client Profile */}
      <Card className="border-0 shadow-lg">
        <CardHeader className="pb-2 border-b">
          <CardTitle className="text-lg flex items-center gap-2">
            <span className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-bold">1</span>
            BASIC CLIENT PROFILE
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-3">
              <div className="flex justify-between py-2 border-b border-dashed">
                <span className="text-slate-600">Preferred Name / Alias</span>
                <span className="font-medium">Anonymous</span>
              </div>
              <div className="flex justify-between py-2 border-b border-dashed">
                <span className="text-slate-600">Age Range</span>
                <span className="font-medium">{assessment.age ? `${assessment.age - 5}-${assessment.age + 5}` : 'Not Provided'}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-dashed">
                <span className="text-slate-600">Gender / Pronouns</span>
                <span className="font-medium">{genderLabels[assessment.gender] || 'Not Specified'}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-dashed">
                <span className="text-slate-600">Location (Optional)</span>
                <span className="font-medium text-slate-400">Not Provided</span>
              </div>
            </div>
            <div className="space-y-3">
              <div className="flex justify-between py-2 border-b border-dashed">
                <span className="text-slate-600">Role Classification</span>
                <span className="font-medium">{sentimentAnalysis?.roleClassification || 'Support Seeker'}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-dashed">
                <span className="text-slate-600">Context Tag</span>
                <Badge variant="outline" className="bg-lavender-50">{focusGroupNames[assessment.final_focus_group]}</Badge>
              </div>
              <div className="flex justify-between py-2 border-b border-dashed">
                <span className="text-slate-600">AI Confidence Level</span>
                <span className="font-medium text-green-600">{sentimentAnalysis?.confidenceLevel || '85'}%</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Section 2: Conversation Summary */}
      <Card className="border-0 shadow-lg">
        <CardHeader className="pb-2 border-b">
          <CardTitle className="text-lg flex items-center gap-2">
            <span className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-bold">2</span>
            CONVERSATION SUMMARY
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4">
          <p className="text-slate-700 leading-relaxed">{conversationSummary}</p>
        </CardContent>
      </Card>

      {/* Section 3: Emotion Trajectory Visualization */}
      <Card className="border-0 shadow-lg">
        <CardHeader className="pb-2 border-b">
          <CardTitle className="text-lg flex items-center gap-2">
            <span className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-bold">3</span>
            EMOTION TRAJECTORY VISUALIZATION
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4 space-y-6">
          {/* Emotion Chart */}
          <div className="h-48 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={emotionTrajectory?.chartData || []}>
                <defs>
                  <linearGradient id="emotionGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <XAxis dataKey="stage" tick={{ fontSize: 11 }} />
                <YAxis domain={[0, 100]} tick={{ fontSize: 11 }} />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: 'white', 
                    border: '1px solid #e2e8f0',
                    borderRadius: '8px',
                    fontSize: '12px'
                  }} 
                />
                <Area 
                  type="monotone" 
                  dataKey="positivity" 
                  stroke="#8b5cf6" 
                  fill="url(#emotionGradient)" 
                  strokeWidth={2}
                  name="Emotional Positivity"
                />
                <Line 
                  type="monotone" 
                  dataKey="stability" 
                  stroke="#22c55e" 
                  strokeWidth={2}
                  dot={{ fill: '#22c55e', r: 4 }}
                  name="Stability"
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          <div className="grid grid-cols-2 gap-6">
            <div className="p-4 rounded-xl bg-slate-50">
              <div className="flex items-center justify-between mb-2">
                <span className="font-semibold text-slate-700">Emotion Stability Index (ESI)</span>
                <span className={`text-2xl font-bold ${getESIColor(emotionTrajectory?.esi || 0)}`}>
                  {emotionTrajectory?.esi || 0}/100
                </span>
              </div>
              <p className="text-sm text-slate-600">{emotionTrajectory?.esiInsight}</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-50">
              <div className="flex items-center justify-between mb-2">
                <span className="font-semibold text-slate-700">Therapeutic Readiness Index (TRI)</span>
                <span className={`text-2xl font-bold ${getTRIColor(emotionTrajectory?.tri || 0)}`}>
                  {emotionTrajectory?.tri || 0}/100
                </span>
              </div>
              <p className="text-sm text-slate-600">{emotionTrajectory?.triInsight}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Section 4: Cognitive and Behavioral Snapshot */}
      <Card className="border-0 shadow-lg">
        <CardHeader className="pb-2 border-b">
          <CardTitle className="text-lg flex items-center gap-2">
            <span className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-bold">4</span>
            COGNITIVE AND BEHAVIORAL SNAPSHOT
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4 space-y-4">
          <div className="p-4 rounded-xl bg-slate-50">
            <div className="flex items-center justify-between mb-2">
              <span className="font-semibold text-slate-700">Behavioral Loop Strength (BLS)</span>
              <span className="text-xl font-bold text-slate-800">{behavioralSnapshot?.bls || 0}/100</span>
            </div>
            <p className="text-sm text-slate-600">{behavioralSnapshot?.blsInsight}</p>
          </div>
          <div className="p-4 rounded-xl bg-slate-50">
            <div className="flex items-center justify-between mb-2">
              <span className="font-semibold text-slate-700">Group Synergy Predictor (GSP)</span>
              <span className="text-xl font-bold text-green-600">{behavioralSnapshot?.gsp || 0}/100</span>
            </div>
            <p className="text-sm text-slate-600">{behavioralSnapshot?.gspInsight}</p>
          </div>
        </CardContent>
      </Card>

      {/* Section 5: Risk & Safety Summary */}
      <Card className="border-0 shadow-lg">
        <CardHeader className="pb-2 border-b">
          <CardTitle className="text-lg flex items-center gap-2">
            <span className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-bold">5</span>
            RISK & SAFETY SUMMARY
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4 space-y-4">
          <div className="flex items-center gap-3">
            <span className="text-slate-600">Nature of Risk:</span>
            <Badge className={getRiskColor(riskSummary?.riskLevel || 'low')}>
              {riskSummary?.natureOfRisk || 'Low - General Support Needed'}
            </Badge>
          </div>
          
          {riskSummary?.alertPhrases?.length > 0 && (
            <div className="p-4 rounded-xl bg-amber-50 border border-amber-200">
              <div className="flex items-center gap-2 mb-2">
                <AlertTriangle className="w-4 h-4 text-amber-600" />
                <span className="font-semibold text-amber-800">Alert Phrases & Risk Indicators</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {riskSummary.alertPhrases.map((phrase, idx) => (
                  <span key={idx} className="px-2 py-1 bg-amber-100 text-amber-800 rounded text-sm">
                    {phrase}
                  </span>
                ))}
              </div>
            </div>
          )}

          <Separator />
          
          <div className="p-4 rounded-xl bg-slate-50 text-sm text-slate-600 italic">
            <p className="mb-2">
              <strong>Privacy & Transparency:</strong> This report is automatically generated using AI insights 
              derived from user-provided data within the Mentra platform. It assists therapists in 
              pre-session preparation and is not a formal diagnosis. Data is anonymized.
            </p>
            <div className="flex items-center gap-2">
              <span>Transparency Score:</span>
              <Badge variant="outline" className="bg-green-50 text-green-700">{riskSummary?.transparencyScore || 95}%</Badge>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Footer & CTA */}
      <Card className="border-0 shadow-lg bg-gradient-to-br from-lavender-50 to-sage-50">
        <CardContent className="py-6">
          <div className="text-center space-y-4">
            <div className="flex items-center justify-center gap-2 text-slate-500 text-sm">
              <Shield className="w-4 h-4" />
              <span>Mentra Confidential ©2026 | All analytics computed under ethical AI compliance.</span>
            </div>
            
            <Button
              onClick={onJoinGroup}
              className="h-12 px-8 bg-gradient-to-r from-lavender-500 to-lavender-600 hover:from-lavender-600 hover:to-lavender-700 text-white rounded-xl shadow-lg"
            >
              Join Your Support Group
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}